##################################################################################################
# cart service and deployment
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: cart
  labels:
    app: cart
    service: cart
spec:
  ports:
  - port: 8081
    targetPort: 8081
    name: grpc
  selector:
    app: cart
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onlineboutique-cart
  labels:
    account: cart
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    app: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      serviceAccountName: onlineboutique-cart
      containers:
      - name: cart
        image: appnetorg/onlineboutique-grpc:latest
        command: ["/app/onlineboutique"]
        args: ["cart"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
---
# volume and persistent volume claim of `cart`
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cart-pv
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: cart-storage
  hostPath:
    path: /data/volumes/cart-pv   # Where all the hard drives are mounted
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cart-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cart-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-redis
  template:
    metadata:
      labels:
        app: cart-redis
    spec:
      containers:
      - name: cart-redis
        image: redis:6.2
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: cart-redis
  namespace: default
spec:
  selector:
    app: cart-redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---