##################################################################################################
# currency service and deployment
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: currency
  labels:
    app: currency
    service: currency
spec:
  ports:
  - port: 8083
    targetPort: 8083
    name: grpc
  selector:
    app: currency
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onlineboutique-currency
  labels:
    account: currency
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency
  labels:
    app: currency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      labels:
        app: currency
    spec:
      serviceAccountName: onlineboutique-currency
      containers:
      - name: currency
        image: appnetorg/onlineboutique-grpc:latest
        command: ["/app/onlineboutique"]
        args: ["currency"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
---
# volume and persistent volume claim of `currency`
apiVersion: v1
kind: PersistentVolume
metadata:
  name: currency-pv
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: currency-storage
  hostPath:
    path: /data/volumes/currency-pv   # Where all the hard drives are mounted
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: currency-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: currency-storage
  resources:
    requests:
      storage: 1Gi
---